// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// median_freq
double median_freq(NumericVector values, IntegerVector freqs);
RcppExport SEXP M3D_median_freq(SEXP valuesSEXP, SEXP freqsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type freqs(freqsSEXP);
    __result = Rcpp::wrap(median_freq(values, freqs));
    return __result;
END_RCPP
}
