// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// median_freq
double median_freq(NumericVector values, IntegerVector freqs);
RcppExport SEXP M3D_median_freq(SEXP valuesSEXP, SEXP freqsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type freqs(freqsSEXP);
    rcpp_result_gen = Rcpp::wrap(median_freq(values, freqs));
    return rcpp_result_gen;
END_RCPP
}
